/**
 * Coverage Analysis Utility for WiFi Planning
 * Telkomsel Corporate Standards
 */

export interface CoverageStats {
    totalPixels: number;
    tooHotZone: number;     // > -45 dBm
    excellentZone: number;  // -45 to -60 dBm
    goodZone: number;       // -60 to -65 dBm
    fairZone: number;       // -65 to -75 dBm
    weakZone: number;       // -75 to -85 dBm
    deadZone: number;       // < -85 dBm
    
    tooHotPercent: number;
    excellentPercent: number;
    goodPercent: number;
    fairPercent: number;
    weakPercent: number;
    deadPercent: number;
}

export function analyzeCoverage(
    signalGrid: Float32Array,
    rows: number,
    cols: number
): CoverageStats {
    let tooHot = 0;
    let excellent = 0;
    let good = 0;
    let fair = 0;
    let weak = 0;
    let dead = 0;

    for (let i = 0; i < signalGrid.length; i++) {
        const val = signalGrid[i];
        if (val > -45) {
            tooHot++;
        } else if (val >= -60) {
            excellent++;
        } else if (val >= -65) {
            good++;
        } else if (val >= -75) {
            fair++;
        } else if (val >= -85) {
            weak++;
        } else {
            dead++;
        }
    }

    const total = signalGrid.length;

    return {
        totalPixels: total,
        tooHotZone: tooHot,
        excellentZone: excellent,
        goodZone: good,
        fairZone: fair,
        weakZone: weak,
        deadZone: dead,
        tooHotPercent: (tooHot / total) * 100,
        excellentPercent: (excellent / total) * 100,
        goodPercent: (good / total) * 100,
        fairPercent: (fair / total) * 100,
        weakPercent: (weak / total) * 100,
        deadPercent: (dead / total) * 100
    };
}

export function generateTextReport(
    aps: any[],
    coverage: CoverageStats,
    frequency: string,
    walls: any[]
): string {
    const report = `
WiFi Coverage Report - Telkomsel Standards
==========================================
Generated: ${new Date().toLocaleString()}

Network Configuration:
- Frequency Band: ${frequency}
- Access Points: ${aps.length}
- Walls/Barriers: ${walls.length}

Coverage Statistics:
- Too Hot (> -45 dBm): ${coverage.tooHotPercent.toFixed(1)}%
- Excellent (-45 to -60 dBm): ${coverage.excellentPercent.toFixed(1)}%
- Good (-60 to -65 dBm): ${coverage.goodPercent.toFixed(1)}%
- Fair (-65 to -75 dBm): ${coverage.fairPercent.toFixed(1)}%
- Weak (-75 to -85 dBm): ${coverage.weakPercent.toFixed(1)}%
- Dead Zone (< -85 dBm): ${coverage.deadPercent.toFixed(1)}%

Total Coverage (Fair or Better): ${(coverage.tooHotPercent + coverage.excellentPercent + coverage.goodPercent + coverage.fairPercent).toFixed(1)}%

Access Point Placements:
${aps.map((ap, i) => `  ${i + 1}. AP at (${Math.round(ap.x / 40)}m, ${Math.round(ap.y / 40)}m) - ${ap.txPower} dBm, Channel ${ap.channel}`).join('\n')}

Recommendations:
${(coverage.excellentPercent + coverage.goodPercent + coverage.fairPercent) < 80 ? '- Consider adding more APs to improve coverage' : '- Coverage is adequate'}
${coverage.weakPercent > 20 ? '- High weak signal zones detected - review AP placement' : ''}
${coverage.deadPercent > 10 ? '- Significant dead zones - add APs or relocate existing ones' : ''}
${coverage.tooHotPercent > 10 ? '- Some areas have very strong signal (Too Hot) - consider lowering Tx Power' : ''}

---
Report generated by WiFi Planner Pro
Telkomsel Corporate Standards
`;

    return report;
}
