/**
 * Coverage Analysis Utility for WiFi Planning
 * Telkomsel Corporate Standards
 */

export interface CoverageStats {
    totalPixels: number;
    excellentZone: number;  // > -60 dBm (green)
    goodZone: number;       // -60 to -70 dBm (yellow)
    weakZone: number;       // -70 to -85 dBm (orange/red)
    deadZone: number;       // < -90 dBm (no signal)
    excellentPercent: number;
    goodPercent: number;
    weakPercent: number;
    deadPercent: number;
}

export function analyzeCoverage(
    signalGrid: Float32Array,
    rows: number,
    cols: number
): CoverageStats {
    let excellent = 0;
    let good = 0;
    let weak = 0;
    let dead = 0;

    for (let i = 0; i < signalGrid.length; i++) {
        const val = signalGrid[i];
        if (val >= -60) {
            excellent++;
        } else if (val >= -70) {
            good++;
        } else if (val >= -85) {
            weak++;
        } else {
            dead++;
        }
    }

    const total = signalGrid.length;

    return {
        totalPixels: total,
        excellentZone: excellent,
        goodZone: good,
        weakZone: weak,
        deadZone: dead,
        excellentPercent: (excellent / total) * 100,
        goodPercent: (good / total) * 100,
        weakPercent: (weak / total) * 100,
        deadPercent: (dead / total) * 100
    };
}

export function generateTextReport(
    aps: any[],
    coverage: CoverageStats,
    frequency: string,
    walls: any[]
): string {
    const report = `
WiFi Coverage Report - Telkomsel Standards
==========================================
Generated: ${new Date().toLocaleString()}

Network Configuration:
- Frequency Band: ${frequency}
- Access Points: ${aps.length}
- Walls/Barriers: ${walls.length}

Coverage Statistics:
- Excellent (-30 to -60 dBm): ${coverage.excellentPercent.toFixed(1)}%
- Good (-60 to -70 dBm): ${coverage.goodPercent.toFixed(1)}%
- Weak (-70 to -85 dBm): ${coverage.weakPercent.toFixed(1)}%
- No Signal (< -90 dBm): ${coverage.deadPercent.toFixed(1)}%

Total Coverage (Usable): ${(coverage.excellentPercent + coverage.goodPercent).toFixed(1)}%

Access Point Placements:
${aps.map((ap, i) => `  ${i + 1}. AP at (${Math.round(ap.x / 40)}m, ${Math.round(ap.y / 40)}m) - ${ap.txPower} dBm, Channel ${ap.channel}`).join('\n')}

Recommendations:
${coverage.excellentPercent + coverage.goodPercent < 80 ? '- Consider adding more APs to improve coverage' : '- Coverage is adequate'}
${coverage.weakPercent > 20 ? '- High weak signal zones detected - review AP placement' : ''}
${coverage.deadPercent > 10 ? '- Significant dead zones - add APs or relocate existing ones' : ''}

---
Report generated by WiFi Planner Pro
Telkomsel Corporate Standards
`;

    return report;
}
